name: Tests

on: push

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        os: [macos-latest]

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Common steps
        id: common
        uses: ghga-de/gh-action-common@v6.0.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Debug
        id: Debug
        if: runner.os == 'macOS'
        run: |
              brew install docker
              brew install colima
              if [ -f ~/.colima/_lima/_networks/user-v2 ]
                rm -rf ~/.colima/_lima/_networks/user-v2
              fi
              colima start

      - name: Install tox plugin
        id: install-tox-gh-actions
        run: |
          pip install --disable-pip-version-check "tox-gh-actions>=3.2,<4"

      - name: Run tests with Python ${{ matrix.python-version }}
        id: pytest
        if: ${{ matrix.python-version != '3.12' }}
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          tox

      - name: Run tests with Python ${{ matrix.python-version }} measuring coverage
        id: pytest-coverage
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          tox -- --cov="${{ steps.common.outputs.PACKAGE_NAME }}" --cov-report=xml


      - name: Upload coverage to coveralls
        id: coveralls
        if: ${{ matrix.python-version == '3.12' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade coveralls
          coveralls --service=github
